# Generated by Django 5.1.3 on 2024-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_creado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='ruts',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='integrantes',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='rut',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
